const questions = [
  {
    question: "Podaj gatunki muzyczne",
    answers: [
      "Rock",
      "Pop",
      "Hip-hop",
      "Jazz",
      "Country",
      "Metal",
      "R&B",
      "Reggae",
      "Klasyczna",
      "Electro",
    ],
    correctAnswers: [],
    wrongAnswers: [],
  },  
  {
    question: "Podaj przedmioty w kuchni",
    answers: [
      "Nóż",
      "Patelnia",
      "Garnek",
      "Talerz",
      "Łyżka",
      "Widelec",
      "Mikrofalówka",
      "Czajnik",
      "Siekacz",
      "Deska do krojenia",
    ],
    correctAnswers: [],
    wrongAnswers: [],
  },
  {
    question: "Podaj znane marki samochodów",
    answers: [
      "Toyota",
      "Ford",
      "Volkswagen",
      "Mercedes-Benz",
      "BMW",
      "Audi",
      "Nissan",
      "Honda",
      "Chevrolet",
      "Volvo",
    ],
    correctAnswers: [],
    wrongAnswers: [],
  },
  {
    question: "Podaj języki świata",
    answers: [
      "Angielski",
      "Hiszpański",
      "Chiński",
      "Arabski",
      "Rosyjski",
      "Francuski",
      "Niemiecki",
      "Japoński",
      "Włoski",
      "Polski",
    ],
    correctAnswers: [],
    wrongAnswers: [],
  },  
];

export default questions;
