const questions = [
  {
    question: "Podaj kolory tęczy",
    answers: [
      "Czerwony",
      "Pomarańczowy",
      "Żółty",
      "Zielony",
      "Niebieski",
      "Fioletowy",
    ],
  },
  {
    question: "Podaj znane zabytki świata",
    answers: [
      "Piramidy w Gizie",
      "Statua Wolności",
      "Wielki Mur Chiński",
      "Machu Picchu",
      "Koloseum w Rzymie",
      "Tadź Mahal",
    ],
  },
  {
    question: "Podaj sporty zimowe",
    answers: [
      "Narciarstwo alpejskie",
      "Snowboard",
      "Hokej na lodzie",
      "Biathlon",
      "Skoki narciarskie",
      "Łyżwiarstwo figurowe",
    ],
  },
  {
    question: "Podaj postacie z filmów Disneya",
    answers: [
      "Myszka Miki",
      "Kopciuszek",
      "Ariel",
      "Simba",
      "Elsa",
      "Aladyn",
      "Pocahontas",
      "Mulan",
      "Pszczółka Maja",
      "Robin Hood",
    ],
  },
  {
    question: "Podaj nazwy owoców tropikalnych",
    answers: [
      "Banany",
      "Mango",
      "Ananas",
      "Kiwi",
      "Papaja",
      "Kokos",
      "Granat",
      "Marakuja",
      "Guawa",
      "Lichi",
    ],
  },
  {
    question: "Podaj nazwy stolic państw europejskich",
    answers: [
      "Warszawa",
      "Paryż",
      "Berlin",
      "Londyn",
      "Rzym",
      "Madryt",
      "Ateny",
      "Oslo",
      "Praga",
      "Budapeszt",
    ],
  },
  {
    question: "Podaj nazwy kontynentów",
    answers: [
      "Afryka",
      "Ameryka Północna",
      "Ameryka Południowa",
      "Azja",
      "Europa",
      "Australia",
      "Antarktyka",
    ],
  },
  {
    question: "Podaj nazwy znanych marek samochodów",
    answers: [
      "Toyota",
      "Ford",
      "Volkswagen",
      "Mercedes-Benz",
      "BMW",
      "Audi",
      "Nissan",
      "Honda",
      "Chevrolet",
      "Volvo",
    ],
  },
  {
    question: "Podaj nazwy filmów z serii 'Gwiezdne Wojny'",
    answers: [
      "Nowa Nadzieja",
      "Imperium Kontratakuje",
      "Powrót Jedi",
      "Mroczne Widmo",
      "Atak Klonów",
      "Zemsta Sithów",
      "Przebudzenie Mocy",
      "Ostatni Jedi",
      "Skywalker. Odrodzenie",
      "Skywalker. Upadek",
    ],
  },
  {
    question: "Podaj nazwy znanych artystów malarzy",
    answers: [
      "Leonardo da Vinci",
      "Vincent van Gogh",
      "Pablo Picasso",
      "Michelangelo",
      "Claude Monet",
      "Salvador Dali",
      "Rembrandt",
      "Georgia O'Keeffe",
      "Frida Kahlo",
      "Edvard Munch",
    ],
  },
  {
    question: "Podaj nazwy krajów Azji",
    answers: [
      "Chiny",
      "Indie",
      "Japonia",
      "Korea Południowa",
      "Rosja",
      "Tajlandia",
      "Wietnam",
      "Arabia Saudyjska",
      "Turcja",
      "Mongolia",
    ],
  },
  {
    question: "Podaj nazwy znanych marek komputerowych",
    answers: [
      "Apple",
      "Microsoft",
      "Dell",
      "HP",
      "Lenovo",
      "Asus",
      "Acer",
      "Samsung",
      "Sony",
      "Toshiba",
    ],
  },
  {
    question: "Podaj nazwy znanych przepisów kuchni włoskiej",
    answers: [
      "Pizza Margherita",
      "Spaghetti Carbonara",
      "Lasagne",
      "Risotto",
      "Tiramisu",
      "Bruschetta",
      "Cannelloni",
      "Panna Cotta",
      "Ossobuco",
      "Caprese",
    ],
  },
  {
    question: "Podaj nazwy planet Układu Słonecznego",
    answers: [
      "Merkury",
      "Wenus",
      "Ziemia",
      "Mars",
      "Jowisz",
      "Saturn",
      "Uran",
      "Neptun",
    ],
  },
  {
    question: "Podaj nazwy znanych marek laptopów",
    answers: [
      "Dell",
      "HP",
      "Lenovo",
      "Apple",
      "Asus",
      "Acer",
      "MSI",
      "Microsoft",
      "Toshiba",
      "Razer",
    ],
  },
  {
    question: "Podaj nazwy znanych gór świata",
    answers: [
      "Mount Everest",
      "K2",
      "Mount McKinley (Denali)",
      "Mount Kilimanjaro",
      "Mont Blanc",
      "Aconcagua",
      "Himalaje",
      "Andes",
      "Kilimandżaro",
      "Alpy",
    ],
  },
  {
    question: "Podaj nazwy znanych filmowych postaci superbohaterów",
    answers: [
      "Spider-Man",
      "Superman",
      "Batman",
      "Wonder Woman",
      "Iron Man",
      "Thor",
      "Captain America",
      "Black Widow",
      "Hulk",
      "Black Panther",
    ],
  },
  {
    question: "Podaj nazwy znanych marek telefonów komórkowych",
    answers: [
      "Apple",
      "Samsung",
      "Huawei",
      "Google",
      "Sony",
      "LG",
      "Motorola",
      "OnePlus",
      "Xiaomi",
      "Nokia",
    ],
  },
  {
    question: "Podaj nazwy znanych marek telefonów komórkowych",
    answers: [
      "Apple",
      "Samsung",
      "Huawei",
      "Google",
      "Sony",
      "LG",
      "Motorola",
      "OnePlus",
      "Xiaomi",
      "Nokia",
    ],
  },
  {
    question: "Podaj nazwy państw Ameryki Południowej",
    answers: [
      "Brazylia",
      "Argentyna",
      "Kolumbia",
      "Peru",
      "Wenezuela",
      "Chile",
      "Ekwador",
      "Boliwia",
      "Paragwaj",
      "Urugwaj",
    ],
  },
  {
    question: "Podaj nazwy znanych marek odzieżowych",
    answers: [
      "Nike",
      "Adidas",
      "Gucci",
      "H&M",
      "Zara",
      "Calvin Klein",
      "Puma",
      "Levi's",
      "Versace",
      "Dior",
    ],
  },
  {
    question: "Podaj nazwy znanych filmów Disneya",
    answers: [
      "Król Lew",
      "Księżniczka Śnieżka",
      "Aladyn",
      "Mała Syrenka",
      "Dzwoneczek",
      "Toy Story",
      "Zootopia",
      "Śpiąca Królewna",
      "Alladin",
      "Krótka, mała Księżniczka",
    ],
  },
  {
    question: "Podaj nazwy znanych marek kosmetycznych",
    answers: [
      "L'Oréal",
      "Maybelline",
      "MAC",
      "Estée Lauder",
      "NARS",
      "Revlon",
      "Clinique",
      "Kiehl's",
      "Sephora",
      "Avon",
    ],
  },
  {
    question: "Podaj nazwy instrumentów muzycznych",
    answers: [
      "Gitara",
      "Pianino",
      "Saksofon",
      "Trąbka",
      "Skrzypce",
      "Bęben",
      "Flet",
      "Harfa",
      "Ksylofon",
      "Bass",
    ],
  },
  {
    question: "Podaj nazwy znanych wynalazków",
    answers: [
      "Żarówka",
      "Telefon",
      "Komputer",
      "Telewizja",
      "Samolot",
      "Lekarstwo penicylina",
      "Mikroskop",
      "Silnik parowy",
      "Internet",
      "Telegraf",
    ],
  },
  {
    question: "Podaj nazwy znanych firm technologicznych",
    answers: [
      "Apple",
      "Microsoft",
      "Google",
      "Amazon",
      "Facebook",
      "Intel",
      "Samsung",
      "Sony",
      "Tesla",
      "SpaceX",
    ],
  },
  {
    question: "Podaj nazwy krajów Afryki",
    answers: [
      "Nigeria",
      "Egipt",
      "Kenia",
      "RPA (Republika Południowej Afryki)",
      "Maroko",
      "Etiopia",
      "Kamerun",
      "Ghana",
      "Algieria",
      "Tunezja",
    ],
  },
  {
    question: "Podaj nazwy znanych marek ubrań sportowych",
    answers: [
      "Nike",
      "Adidas",
      "Puma",
      "Reebok",
      "Under Armour",
      "New Balance",
      "Fila",
      "Lululemon",
      "Converse",
      "Skechers",
    ],
  },
  {
    question: "Podaj nazwy znanych gier komputerowych",
    answers: [
      "The Witcher 3: Dziki Gon",
      "Grand Theft Auto V",
      "Minecraft",
      "Fortnite",
      "League of Legends",
      "Overwatch",
      "Call of Duty: Warzone",
      "Cyberpunk 2077",
      "Among Us",
      "World of Warcraft",
    ],
  },
  {
    question: "Podaj nazwy znanych rzeźb i pomników",
    answers: [
      "Statua Wolności",
      "Mona Lisa",
      "Posąg Dawida",
      "Arka Triumfalna",
      "Rzeźba Chrystusa Odkupiciela",
      "Syrena Warszawska",
      "Rzeźba Nike z Samotraki",
      "Mauzoleum w Halikarnasie",
      "Rzeźba Auguste'a Rodina 'Myśliciel'",
      "Pomnik Jezusa Chrystusa w Rio de Janeiro",
    ],
  },
  {
    question: "Podaj nazwy znanych marek zegarków",
    answers: [
      "Rolex",
      "Omega",
      "Tag Heuer",
      "Casio",
      "Patek Philippe",
      "Audemars Piguet",
      "Breitling",
      "Seiko",
      "Fossil",
      "Tissot",
    ],
  },
  {
    question: "Podaj nazwy znanych znaków zodiaku",
    answers: [
      "Baran",
      "Byk",
      "Bliźnięta",
      "Rak",
      "Lew",
      "Panna",
      "Waga",
      "Skorpion",
      "Strzelec",
      "Koziorożec",
      "Wodnik",
      "Ryby",
    ],
  },
  {
    question: "Podaj nazwy znanych aktorów filmowych",
    answers: [
      "Tom Hanks",
      "Meryl Streep",
      "Leonardo DiCaprio",
      "Jennifer Lawrence",
      "Denzel Washington",
      "Scarlett Johansson",
      "Robert De Niro",
      "Natalie Portman",
      "Johnny Depp",
      "Cate Blanchett",
    ],
  },
  {
    question: "Podaj nazwy znanych kompozytorów muzyki klasycznej",
    answers: [
      "Ludwig van Beethoven",
      "Wolfgang Amadeusz Mozart",
      "Johann Sebastian Bach",
      "Pyotr Czajkowski",
      "Claude Debussy",
      "Frederic Chopin",
      "Antonio Vivaldi",
      "Igor Strawiński",
      "Gustav Mahler",
      "Richard Wagner",
    ],
  },
  {
    question: "Podaj nazwy znanych marek aparatów fotograficznych",
    answers: [
      "Canon",
      "Nikon",
      "Sony",
      "Fujifilm",
      "Panasonic",
      "Olympus",
      "Leica",
      "Pentax",
      "Hasselblad",
      "Ricoh",
    ],
  },
  {
    question: "Podaj nazwy znanych przysmaków kuchni francuskiej",
    answers: [
      "Bagietka",
      "Krokiet z kurczaka",
      "Ratatouille",
      "Tarta tatin",
      "Foie gras",
      "Krewetki w czosnku",
      "Cassoulet",
      "Quiche Lorraine",
      "Coq au Vin",
      "Crème brûlée",
    ],
  },
  {
    question: "Podaj nazwy znanych rodzajów tańca",
    answers: [
      "Walce",
      "Tango",
      "Salsa",
      "Hip-hop",
      "Breakdance",
      "Bale",
      "Flamenco",
      "Cha-cha",
      "Samba",
      "Jive",
    ],
  },
  {
    question: "Podaj nazwy znanych gatunków zwierząt morskich",
    answers: [
      "Delfin",
      "Rekin",
      "Żółw morski",
      "Okrętka",
      "Morski konik",
      "Meduza",
      "Krab",
      "Rozgwiazda",
      "Morski diabeł",
      "Koralowiec",
    ],
  },
  {
    question: "Podaj nazwy znanych aktorek filmowych",
    answers: [
      "Meryl Streep",
      "Scarlett Johansson",
      "Natalie Portman",
      "Cate Blanchett",
      "Julia Roberts",
      "Angelina Jolie",
      "Jennifer Lawrence",
      "Charlize Theron",
      "Nicole Kidman",
      "Kate Winslet",
    ],
  },
  {
    question: "Podaj nazwy znanych aktorek filmowych",
    answers: [
      "Meryl Streep",
      "Scarlett Johansson",
      "Natalie Portman",
      "Cate Blanchett",
      "Julia Roberts",
      "Angelina Jolie",
      "Jennifer Lawrence",
      "Charlize Theron",
      "Nicole Kidman",
      "Kate Winslet",
    ],
  },
  {
    question: "Podaj nazwy znanych wynalazków XX wieku",
    answers: [
      "Samolot",
      "Telewizja",
      "Komputer osobisty",
      "Internet",
      "Telefon komórkowy",
      "Szczepionka przeciwko polio",
      "Lądowanie na Księżycu",
      "Mikroprocesor",
      "Klonowanie owcy Dolly",
      "Penicillin",
    ],
  },
  {
    question: "Podaj nazwy znanych aktorów komediowych",
    answers: [
      "Jim Carrey",
      "Will Ferrell",
      "Adam Sandler",
      "Seth Rogen",
      "Melissa McCarthy",
      "Kevin Hart",
      "Tina Fey",
      "Steve Carell",
      "Amy Schumer",
      "Sacha Baron Cohen",
    ],
  },
  {
    question: "Podaj nazwy znanych górskich szczytów",
    answers: [
      "Mount Everest",
      "K2",
      "Annapurna",
      "Kilimandżaro",
      "Mont Blanc",
      "Mount McKinley (Denali)",
      "Mount Fuji",
      "Matterhorn",
      "Elbrus",
      "Aconcagua",
    ],
  },
  {
    question: "Podaj nazwy znanych postaci z mitologii nordyckiej",
    answers: [
      "Thor",
      "Odin",
      "Loki",
      "Freja",
      "Fenrir",
      "Yggdrasil",
      "Balder",
      "Jotnar",
      "Valkirie",
      "Heimdall",
    ],
  },
  {
    question: "Podaj nazwy znanych marek zegarków luksusowych",
    answers: [
      "Rolex",
      "Patek Philippe",
      "Audemars Piguet",
      "Omega",
      "Cartier",
      "Hublot",
      "IWC",
      "Jaeger-LeCoultre",
      "Tag Heuer",
      "Panerai",
    ],
  },
  {
    question: "Podaj nazwy znanych rodzajów win",
    answers: [
      "Cabernet Sauvignon",
      "Merlot",
      "Chardonnay",
      "Pinot Noir",
      "Sauvignon Blanc",
      "Syrah",
      "Zinfandel",
      "Riesling",
      "Malbec",
      "Tempranillo",
    ],
  },
  {
    question: "Podaj nazwy znanych marek aparatów telefonicznych",
    answers: [
      "Apple iPhone",
      "Samsung Galaxy",
      "Google Pixel",
      "OnePlus",
      "Sony Xperia",
      "Huawei Mate",
      "LG G",
      "Xiaomi Mi",
      "Nokia Lumia",
      "Motorola Moto",
    ],
  },
  {
    question: "Podaj nazwy znanych zjawisk przyrodniczych",
    answers: [
      "Eksploracja kosmosu",
      "Huragan",
      "Trzęsienie ziemi",
      "Tornado",
      "Błyskawica",
      "Aurora polarna",
      "Kometa",
      "Cyklon",
      "Prąd morski",
      "Zorza polarna",
    ],
  },
  {
    question: "Podaj nazwy znanych dzieł sztuki",
    answers: [
      "Mona Lisa",
      "Starry Night",
      "Nocne strażnicy",
      "Dziewczyna z perłą",
      "Guernica",
      "Bitwa pod San Romano",
      "Złota godzina",
      "Portret Doriana Graya",
      "Astronoma",
      "Trzy muzy",
    ],
  },
  {
    question: "Podaj nazwy znanych aktorek telewizyjnych",
    answers: [
      "Emilia Clarke",
      "Jennifer Aniston",
      "Sophie Turner",
      "Viola Davis",
      "Nicole Kidman",
      "Kerry Washington",
      "Elisabeth Moss",
      "Phoebe Waller-Bridge",
      "Zendaya",
      "Laura Linney",
    ],
  },
  {
    question: "Podaj nazwy znanych gatunków filmowych",
    answers: [
      "Science fiction",
      "Fantasy",
      "Dramat",
      "Komedia",
      "Horror",
      "Akcja",
      "Thriller",
      "Kryminał",
      "Animacja",
      "Dokumentalny",
    ],
  },
  {
    question: "Podaj nazwy znanych marek perfum",
    answers: [
      "Chanel",
      "Dior",
      "Gucci",
      "Versace",
      "Calvin Klein",
      "Yves Saint Laurent",
      "Estée Lauder",
      "Paco Rabanne",
      "Burberry",
      "Armani",
    ],
  },
  {
    question: "Podaj nazwy znanych gatunków ptaków",
    answers: [
      "Orzeł",
      "Sokół",
      "Pingwin cesarski",
      "Kruk",
      "Kanarek",
      "Kaczka krzyżówka",
      "Słowik",
      "Kormoran",
      "Gołąb",
      "Żuraw",
    ],
  },
  {
    question: "Podaj nazwy znanych gier planszowych",
    answers: [
      "Catan",
      "Monopoly",
      "Szachy",
      "Uno",
      "Ticket to Ride",
      "Dixit",
      "Scrabble",
      "Carcassonne",
      "Puerto Rico",
      "Agricola",
    ],
  },
  {
    question: "Podaj nazwy znanych instrumentów muzycznych",
    answers: [
      "Gitara",
      "Fortepian",
      "Skrzypce",
      "Trąbka",
      "Bęben",
      "Flet",
      "Harfa",
      "Saksofon",
      "Klarnet",
      "Didgeridoo",
    ],
  },
  {
    question: "Podaj nazwy znanych marek samochodów",
    answers: [
      "Toyota",
      "Volkswagen",
      "Ford",
      "Honda",
      "BMW",
      "Mercedes-Benz",
      "Audi",
      "Chevrolet",
      "Subaru",
      "Hyundai",
    ],
  },
  {
    question: "Podaj nazwy znanych piłkarzy",
    answers: [
      "Lionel Messi",
      "Cristiano Ronaldo",
      "Neymar",
      "Mohamed Salah",
      "Kylian Mbappé",
      "Robert Lewandowski",
      "Sergio Ramos",
      "Kevin De Bruyne",
      "Harry Kane",
      "Luka Modrić",
    ],
  },
  {
    question: "Podaj nazwy znanych marek kosmetyków",
    answers: [
      "L'Oréal",
      "Maybelline",
      "MAC",
      "Estée Lauder",
      "Clinique",
      "NARS",
      "Revlon",
      "Urban Decay",
      "Too Faced",
      "Kiehl's",
    ],
  },
  {
    question: "Podaj nazwy znanych rodzajów herbaty",
    answers: [
      "Earl Grey",
      "Zielona herbata",
      "Czarna herbata",
      "Rooibos",
      "Mint tea",
      "Oolong",
      "Chai",
      "Jasminowa herbata",
      "Biała herbata",
      "Pu-erh",
    ],
  },
  {
    question: "Podaj nazwy znanych komediantów stand-upowych",
    answers: [
      "Dave Chappelle",
      "Kevin Hart",
      "Amy Schumer",
      "John Mulaney",
      "Trevor Noah",
      "Hannah Gadsby",
      "Iliza Shlesinger",
      "Aziz Ansari",
      "Ricky Gervais",
      "Louis C.K.",
    ],
  },
  {
    question: "Podaj nazwy znanych gatunków muzyki",
    answers: [
      "Rock",
      "Pop",
      "Hip-hop",
      "Jazz",
      "Blues",
      "Klasyczna",
      "R&B",
      "Reggae",
      "Country",
      "Electronica",
    ],
  },
  {
    question: "Podaj nazwy znanych gatunków kwiatów",
    answers: [
      "Róża",
      "Tulipan",
      "Fiołek",
      "Mak",
      "Narcyz",
      "Chryzantema",
      "Lilia",
      "Słonecznik",
      "Orchidea",
      "Goździk",
      "Irys",
      "Stokrotka",
    ],
  },
  {
    question: "Podaj nazwy znanych gatunków ryb",
    answers: [
      "Łosoś",
      "Tuńczyk",
      "Dorsz",
      "Śledź",
      "Karp",
      "Sum",
      "Pstrąg",
      "Krewetka",
      "Makrela",
      "Szprot",
      "Amur",
      "Okon",
    ],
  },
  {
    question: "Podaj nazwy znanych filmów historycznych",
    answers: [
      "Gladiator",
      "Braveheart",
      "Troy",
      "Pianista",
      "Lincoln",
      "Apocalypto",
      "Amadeus",
      "Elizabeth",
      "Gandhi",
      "Pearl Harbor",
      "Spartacus",
      "300",
    ],
  },
  {
    question: "Podaj nazwy znanych marek perfum męskich",
    answers: [
      "Dior Sauvage",
      "Acqua di Giò",
      "Chanel Bleu de Chanel",
      "Paco Rabanne 1 Million",
      "Creed Aventus",
      "Versace Eros",
      "Tom Ford Noir",
      "Armani Code",
      "Yves Saint Laurent La Nuit de l'Homme",
      "Calvin Klein Eternity for Men",
      "Hugo Boss Bottled",
      "Prada Luna Rossa",
    ],
  },
  {
    question: "Podaj nazwy znanych marek laptopów",
    answers: [
      "Apple MacBook",
      "Dell XPS",
      "HP Spectre",
      "Lenovo ThinkPad",
      "Acer Predator",
      "Asus ZenBook",
      "Microsoft Surface",
      "Razer Blade",
      "MSI GS",
      "LG Gram",
      "Huawei MateBook",
      "Google Pixelbook",
    ],
  },
  {
    question: "Podaj nazwy znanych krajów w Europie",
    answers: [
      "Polska",
      "Niemcy",
      "Francja",
      "Hiszpania",
      "Włochy",
      "Wielka Brytania",
      "Rosja",
      "Ukraina",
      "Turcja",
      "Szwecja",
    ],
  },
  {
    question: "Podaj nazwy znanych gwiazd na niebie",
    answers: [
      "Słońce",
      "Księżyc",
      "Wenus",
      "Mars",
      "Jowisz",
      "Saturn",
      "Uran",
      "Neptun",
      "Pluton",
    ],
  },
  {
    question: "Podaj nazwy znanych zwierząt domowych",
    answers: [
      "Pies",
      "Kot",
      "Królik",
      "Chomik",
      "Ptak",
      "Ryba",
      "Żółw",
      "Konie",
      "Kura",
    ],
  },
  {
    question: "Podaj nazwy znanych owoców",
    answers: [
      "Jabłko",
      "Gruszka",
      "Pomarańcza",
      "Banan",
      "Truskawka",
      "Malina",
      "Borówka",
      "Winogrona",
      "Arbuz",
    ],
  },
  {
    question: "Podaj nazwy znanych warzyw",
    answers: [
      "Marchew",
      "Cebula",
      "Ogórek",
      "Pomidory",
      "Ziemniaki",
      "Papryka",
      "Kapusta",
      "Cukinia",
      "Sałata",
    ],
  },
  {
    question: "Podaj nazwy znanych potraw polskich",
    answers: [
      "Pierogi",
      "Zupa pomidorowa",
      "Kotlet schabowy",
      "Kiełbasa z grilla",
      "Bigos",
      "Placki ziemniaczane",
      "Chłodnik",
      "Lody",
      "Sernik",
    ],
  },
  {
    question: "Podaj nazwy znanych filmów animowanych",
    answers: [
      "Król Lew",
      "Toy Story",
      "Kraina Lodu",
      "Spider-Man: Film",
      "Shrek",
      "Miś Uszatek",
      "Tygrys i przyjaciele",
      "Auta",
      "Madagaskar",
    ],
  },
  {
    question: "Podaj nazwy znanych postaci z bajek",
    answers: [
      "Księżniczka Śnieżka",
      "Mały Książę",
      "Harry Potter",
      "Czerwony Kapturek",
      "Królewna Śnieżka",
      "Księżniczka Aurora",
      "Księżniczka Ariel",
      "Księżniczka Bella",
      "Księżniczka Pocahontas",
    ],
  },
  {
    question: "Podaj nazwy znanych piosenek polskich",
    answers: [
      "Niech żyje wolność",
      "Czerwone maki na Monte Cassino",
      "Jak nie to ja, to kto",
      "Mała dziewczynka z okienkiem",
      "Wszystko mi mówi, że mnie kochasz",
      "Nie ma jak u mamy",
      "Rzuć to wszystko co złe",
      "Miłość w Zakopanem",
      "Taniec w deszczu",
    ],
  },
  {
    question: "Podaj nazwy znanych polskich miast",
    answers: [
      "Warszawa",
      "Kraków",
      "Łódź",
      "Wrocław",
      "Poznań",
      "Gdańsk",
      "Sopot",
      "Szczecin",
      "Bydgoszcz",
    ],
  },
  {
    question: "Podaj nazwy znanych polskich rzek",
    answers: [
      "Wisła",
      "Odra",
      "Warta",
      "Nysa Łużycka",
      "Pełnia",
      "Bug",
      "San",
      "Dniestr",
      "Dunajec",
    ],
  },
  {
    question: "Podaj nazwy znanych polskich gór",
    answers: [
      "Tatry",
      "Karkonosze",
      "Bieszczady",
      "Góry Świętokrzyskie",
      "Góry Sudety",
      "Góry Jurajskie",
      "Góry Świętokrzyskie",
      "Góry Izerskie",
      "Góry Łużyckie",
    ],
  },
  {
    question: "Podaj nazwy znanych polskich zabytków",
    answers: [
      "Zamek Królewski na Wawelu",
      "Stare Miasto w Krakowie",
      "Stare Miasto w Gdańsku",
      "Zamek w Malborku",
      "Zamek w Zamościu",
      "Zamek w Niepołomicach",
      "Bazylika Mariacka w Gdańsku",
      "Katedra Wawelska",
      "Kościół Mariacki w Krakowie",
    ],
  },
  {
    question: "Podaj nazwy znanych polskich postaci historycznych",
    answers: [
      "Jan III Sobieski",
      "Władysław Jagiełło",
      "Mikołaj Kopernik",
      "Adam Mickiewicz",
      "Fryderyk Chopin",
      "Maria Skłodowska-Curie",
      "Józef Piłsudski",
      "Lech Wałęsa",
      "Władysław Gomułka",
    ],
  },
  {
    question: "Podaj nazwy znanych polskich sportowców",
    answers: [
      "Robert Lewandowski",
      "Iga Świątek",
      "Kamil Stoch",
      "Adam Małysz",
      "Justyna Kowalczyk",
      "Paweł Fajdek",
      "Anita Włodarczyk",
      "Bartosz Kurek",
      "Marcin Gortat",
    ],
  },
  {
    question: "Podaj nazwy znanych polskich zespołów muzycznych",
    answers: [
      "Lady Pank",
      "Maanam",
      "Perfect",
      "Bajm",
      "Kult",
      "Hey",
      "Myslovitz",
      "Zakopower",
      "Taco Hemingway",
    ],
  },
  {
    question: "Podaj nazwy znanych polskich filmów",
    answers: [
      "Pan Tadeusz",
      "Czterej pancerni i pies",
      "Sami swoi",
      "Lotna",
      "Noce i dnie",
      "Życie jest piękne",
      "Katyń",
      "Ida",
      "Zimna wojna",
    ],
  },
  {
    question: "Podaj nazwy znanych polskich seriali telewizyjnych",
    answers: [
      "Ranczo",
      "Rodzinka.pl",
      "Świat według Kiepskich",
      "Blondynka",
      "Czas honoru",
      "Wojna i miłość",
      "Na dobre i na złe",
      "M jak miłość",
      "Przyjaciółki",
    ],
  },
];

export default questions;
